/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'createdAt' : bigint,
  'appointmentDate' : string,
  'appointmentTime' : string,
  'appointmentType' : string,
  'address' : string,
  'notes' : string,
  'patientName' : string,
  'phone' : string,
}
export interface Report {
  'id' : bigint,
  'patientAge' : string,
  'referringDoctor' : string,
  'impression' : string,
  'patientGender' : string,
  'createdAt' : bigint,
  'technique' : string,
  'updatedAt' : bigint,
  'isNormal' : boolean,
  'indication' : string,
  'patientName' : string,
  'findings' : string,
  'examDate' : string,
  'examType' : string,
}
export interface Template {
  'id' : bigint,
  'impression' : string,
  'name' : string,
  'technique' : string,
  'indication' : string,
  'findings' : string,
  'examType' : string,
}
export interface _SERVICE {
  'createAppointment' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'createReview' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    bigint
  >,
  'deleteAppointment' : ActorMethod<[bigint], undefined>,
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getReport' : ActorMethod<[bigint], Report>,
  'getTemplate' : ActorMethod<[bigint], Template>,
  'getTemplates' : ActorMethod<[], Array<Template>>,
  'listAppointments' : ActorMethod<[], Array<Appointment>>,
  'listReports' : ActorMethod<[], Array<Report>>,
  'updateReport' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];