/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Report = IDL.Record({
  'id' : IDL.Nat,
  'patientAge' : IDL.Text,
  'referringDoctor' : IDL.Text,
  'impression' : IDL.Text,
  'patientGender' : IDL.Text,
  'createdAt' : IDL.Int,
  'technique' : IDL.Text,
  'updatedAt' : IDL.Int,
  'isNormal' : IDL.Bool,
  'indication' : IDL.Text,
  'patientName' : IDL.Text,
  'findings' : IDL.Text,
  'examDate' : IDL.Text,
  'examType' : IDL.Text,
});
export const Template = IDL.Record({
  'id' : IDL.Nat,
  'impression' : IDL.Text,
  'name' : IDL.Text,
  'technique' : IDL.Text,
  'indication' : IDL.Text,
  'findings' : IDL.Text,
  'examType' : IDL.Text,
});

export const idlService = IDL.Service({
  'createReport' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
  'getTemplate' : IDL.Func([IDL.Nat], [Template], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'updateReport' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'patientAge' : IDL.Text,
    'referringDoctor' : IDL.Text,
    'impression' : IDL.Text,
    'patientGender' : IDL.Text,
    'createdAt' : IDL.Int,
    'technique' : IDL.Text,
    'updatedAt' : IDL.Int,
    'isNormal' : IDL.Bool,
    'indication' : IDL.Text,
    'patientName' : IDL.Text,
    'findings' : IDL.Text,
    'examDate' : IDL.Text,
    'examType' : IDL.Text,
  });
  const Template = IDL.Record({
    'id' : IDL.Nat,
    'impression' : IDL.Text,
    'name' : IDL.Text,
    'technique' : IDL.Text,
    'indication' : IDL.Text,
    'findings' : IDL.Text,
    'examType' : IDL.Text,
  });
  
  return IDL.Service({
    'createReport' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
    'getTemplate' : IDL.Func([IDL.Nat], [Template], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'updateReport' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };